version: '1.25'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    ports:
      - "3333:3333"
    depends_on:
      - redis
      - postgres
    networks:
      - gateway
    command: yarn sequelize db:migrate && yarn sequelize db:seed:all && yarn queue
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - redis
    networks:
      - gateway
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5435:5432
    restart: on-failure:3
    networks:
      - gateway
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - gateway
volumes:
  redis:
  redis-config:
networks:
  gateway: {}